=== Secteur1/evalsmsi/data/quiz.schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://example.com/root.json",
	"type": "array",
	"title": "EvalSMSI Quiz Schema",
	"items": {
		"$id": "#/items",
		"type": "object",
		"title": "Domain Schema",
		"required": [
			"numero",
			"libelle",
			"abrege",
			"subdomains"
		],
		"properties": {
			"numero": {
				"$id": "#/items/properties/numero",
				"type": "integer",
				"title": "Domain Number"
			},
			"libelle": {
				"$id": "#/items/properties/libelle",
				"type": "string",
				"title": "Domain Wording",
				"default": "",
				"pattern": "^(.*)$"
			},
			"abrege": {
				"$id": "#/items/properties/abrege",
				"type": "string",
				"title": "Domain Abstract",
				"default": "",
				"pattern": "^(.*)$"
			},
			"subdomains": {
				"$id": "#/items/properties/subdomains",
				"type": "array",
				"title": "Subdomain Schema",
				"items": {
					"$id": "#/items/properties/subdomains/items",
					"type": "object",
					"title": "Subdomain Schema",
					"required": [
						"numero",
						"libelle",
						"comment",
						"questions"
					],
					"properties": {
						"numero": {
							"$id": "#/items/properties/subdomains/items/properties/numero",
							"type": "integer",
							"title": "SubDomain Number"
						},
						"libelle": {
							"$id": "#/items/properties/subdomains/items/properties/libelle",
							"type": "string",
							"title": "SubDomain Wording",
							"default": "",
							"pattern": "^(.*)$"
						},
						"comment": {
							"$id": "#/items/properties/subdomains/items/properties/comment",
							"type": "string",
							"title": "SubDomain Comment",
							"default": "",
							"pattern": "^(.*)$"
						},
						"questions": {
							"$id": "#/items/properties/subdomains/items/properties/questions",
							"type": "array",
							"title": "Questions Schema",
							"items": {
								"$id": "#/items/properties/subdomains/items/properties/questions/items",
								"type": "object",
								"title": "Questions Schema",
								"required": [
									"numero",
									"libelle",
									"mesure",
									"poids",
									"level"
								],
								"properties": {
									"numero": {
										"$id": "#/items/properties/subdomains/items/properties/questions/items/properties/numero",
										"type": "integer",
										"title": "Question Number"
									},
									"libelle": {
										"$id": "#/items/properties/subdomains/items/properties/questions/items/properties/libelle",
										"type": "string",
										"title": "Question Wording",
										"default": "",
										"pattern": "^(.*)$"
									},
									"mesure": {
										"$id": "#/items/properties/subdomains/items/properties/questions/items/properties/mesure",
										"type": "string",
										"title": "Question Recommandation",
										"default": "",
										"pattern": "^(.*)$"
									},
									"poids": {
										"$id": "#/items/properties/subdomains/items/properties/questions/items/properties/poids",
										"type": "integer",
										"title": "Question Weight"
									},
									"level": {
										"$id": "#/items/properties/subdomains/items/properties/questions/items/properties/level",
										"type": "integer",
										"title": "Question Level"
									}
								}
							}
						}
					}
				}
			}
		}
	}
}

=== Secteur1/evalsmsi/data/lpm_siiv_finance.quiz.json
[
	{
		"numero": 1,
		"libelle": "Règle relative à la politique de sécurité des systèmes d'information",
		"abrege": "Règle 1 - PSSI",
		"subdomains": [
			{
				"numero": 1,
				"libelle": "La PSSI",
				"comment": "L'opérateur élabore, tient à jour et met en oeuvre une politique de sécurité des systèmes d'information. La PSSI décrit l'ensemble des moyens organisationnels et techniques mis en oeuvre par l'opérateur afin d'assurer la sécurité de ses systèmes d'information d'importance vitale.",
				"questions": [
					{
						"numero": 1,
						"libelle": "La PSSI précise les objectifs et les orientations stratégiques en matière de sécurité des SIIV.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 2,
						"libelle": "La PSSI décrit l'organisation de la gouvernance de la sécurité et notamment les rôles et les responsabilités du personnel interne et du personnel externe (prestataires, fournisseurs, etc.) à l'égard de la sécurité des SIIV.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 3,
						"libelle": "La PSSI prévoit un plan de sensibilisation à la sécurité des SIIV au profit de l'ensemble du personnel ainsi qu'un plan de formation à la sécurité des SIIV au profit des personnes ayant des responsabilités particulières, notamment les personnes en charge de l'administration et de la sécurité des SIIV et les utilisateurs disposant de droits d'accès privilégiés aux SIIV.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 4,
						"libelle": "La PSSI fixe les mesures de sécurité générales, notamment en matière de contrôle du personnel interne et du personnel externe, de sécurité physique des SIIV, de gestion des ressources matérielles et logicielles, de gestion de l'assistance technique, de contrôle d'accès aux SIIV, d'exploitation et d'administration des SIIV, de cryptographie, de sécurité des communications et de sécurité des processus de développement.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 5,
						"libelle": "La PSSI définit la procédure d'homologation de sécurité des SIIV.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 6,
						"libelle": "La PSSI définit les procédures d'évaluation des risques en matière de sécurité des SIIV.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 7,
						"libelle": "La PSSI définit les procédures de contrôle et d'audit de la sécurité des SIIV.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 8,
						"libelle": "La PSSI définit la procédure de maintien en conditions de sécurité des ressources des SIIV.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 9,
						"libelle": "La PSSI définit la procédure de traitement des incidents de sécurité.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 10,
						"libelle": "La PSSI définit les procédures de gestion de crises en cas d'attaques informatiques et de continuité d'activité.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 11,
						"libelle": "La PSSI et ses documents d'application sont approuvés formellement par la direction de l'opérateur.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 12,
						"libelle": "L'opérateur élabore au profit de sa direction, au moins annuellement, un rapport sur la mise en oeuvre de la PSSI et de ses documents d'application.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 13,
						"libelle": "Ce rapport précise notamment l'état des lieux des risques, le niveau de sécurité des SIIV et les actions de sécurisation menées.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 14,
						"libelle": "La PSSI, ses documents d'application et les rapports sur leur mise en oeuvre sont tenus à la disposition de l'ANSSI.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					}
				]
			}
		]
	},
	{
		"numero": 2,
		"libelle": "Règle relative à l'homologation de sécurité",
		"abrege": "Règle 2 - Homologation",
		"subdomains": [
			{
				"numero": 1,
				"libelle": "Le dossier d'homologation",
				"comment": "L'opérateur prend la décision d'homologuer un SIIV sur la base du dossier d'homologation.",
				"questions": [
					{
						"numero": 1,
						"libelle": "Le dossier d'homologation comporte l'analyse de risques et les objectifs de sécurité du SIIV.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 2,
						"libelle": "Le dossier d'homologation comporte les mesures de sécurité appliquées au SIIV.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 3,
						"libelle": "Le dossier d'homologation comporte les rapports d'audit de la sécurité du SIIV.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 4,
						"libelle": "Le dossier d'homologation comporte les risques résiduels et les raisons justifiant leur acceptation.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					}
				]
			},
			{
				"numero": 2,
				"libelle": "Le processus d'homologation",
				"comment": "L'opérateur procède à l'homologation de sécurité de chaque SIIV, en mettant en oeuvre la procédure d'homologation prévue par sa politique de sécurité des systèmes d'information. L'homologation d'un système est une décision formelle prise par l'opérateur qui atteste que les risques pesant sur la sécurité de ce système ont été identifiés et que les mesures nécessaires pour le protéger sont mises en oeuvre. Elle atteste également que les éventuels risques résiduels ont été identifiés et acceptés par l'opérateur.",
				"questions": [
					{
						"numero": 1,
						"libelle": "L'homologation est valable pour une durée maximale de trois ans et est renouvelée au terme de cette période.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 2,
						"libelle": "La validité de l'homologation est réexaminée par l'opérateur lors de chaque événement ou évolution de nature à modifier le contexte décrit dans le dossier d'homologation.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 3,
						"libelle": "L'opérateur tient à la disposition de l'ANSSI les décisions et dossiers d'homologation, notamment les rapports d'audit.",
						"mesure": "Ces documents confidentiels sont susceptibles de contenir des informations dont la révélation est réprimée par les dispositions de l'article 226-13 du code pénal. Ils sont, le cas échéant, couverts par le secret de la défense nationale. La présente règle relative à l'homologation s'applique sans préjudice des dispositions prévues par l'arrêté du 30 novembre 2011 portant approbation de l'instruction générale interministérielle n° 1300 sur la protection du secret de la défense nationale, en matière d'homologation des systèmes d'information traitant des informations classifiées.",
						"poids": 1,
						"level": 1
					}
				]
			},
			{
				"numero": 3,
				"libelle": "L'audit d'homologation",
				"comment": "Dans le cadre de l'homologation, un audit de la sécurité du SIIV doit être réalisé. Cet audit vise à vérifier l'application et l'efficacité des mesures de sécurité du SIIV et notamment le respect des règles de sécurité mentionnées dans le présent arrêté. L'audit doit permettre d'évaluer le niveau de sécurité du SIIV au regard des menaces et des vulnérabilités connues.",
				"questions": [
					{
						"numero": 1,
						"libelle": "Un audit de la sécurité du SIIV a été réalisé.",
						"mesure": "L'opérateur peut réaliser lui-même l'audit ou recourir à un prestataire qualifié dans les conditions prévues au chapitre III du décret n°2015-350 du 27 mars 2015 précité.",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 2,
						"libelle": "L'audit de la sécurité comporte la réalisation d'un audit d'architecture.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 3,
						"libelle": "L'audit de la sécurité comporte la réalisation d'un audit de configuration.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 4,
						"libelle": "L'audit de la sécurité comporte la réalisation d'un audit organisationnel.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 5,
						"libelle": "L'audit de la sécurité comporte la réalisation d'un audit physique.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 6,
						"libelle": "L'audit de la sécurité comporte la réalisation de tests de vulnérabilité.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 7,
						"libelle": "L'audit de la sécurité comporte la réalisation de tests d'intrusion.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 8,
						"libelle": "L'audit a été réalisé dans le respect des règles fixées par le référentiel en matière d'audit de sécurité des systèmes d'information prévu à l'article 10 du décret n°2015-350 du 27 mars 2015 relatif à la qualification des produits de sécurité et des prestataires de service de confiance pour les besoins de la sécurité nationale.",
						"mesure": "Néant",
						"poids": 1,
						"level": 1
					},
					{
						"numero": 9,
						"libelle": "A l'issue de l'audit, l'opérateur ou, le cas échéant, le prestataire élabore un rapport d'audit qui expose les constatations sur les mesures appliquées et sur le respect des règles de sécurité.",
						"mesure": "Néant",
						"poids": 1,
